name = "teo-studio-api"
main = "worker.js"
compatibility_date = "2026-09-16"

[[d1_databases]]
binding = "DB"
database_name = "teo-studio-db"
database_id = "ae5d9554-7cf7-417a-9ae7-5ea6ec193c9d"

[vars]
# Do not put secrets here. Set GOOGLE_CLIENT_ID, SESSION_SECRET and LINK4M_API with wrangler secret put.
ADMIN_EMAIL = "YOUR_ADMIN_EMAIL@gmail.com"
